language: node_js
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
before_install:
  - nvm install-latest-npm
before_script:
  - if [ -n "${ESLINT-}" ]; then npm install --no-save "eslint@${ESLINT}"; fi
script:
  - if [ "${LINT-}" = true ]; then npm run lint; fi
  - if [ "${TEST-}" = true ]; then npm test; fi
sudo: false
env:
  global:
    - TEST=true
  matrix:
    - ESLINT=6
    - ESLINT=5
    - ESLINT=4
    - ESLINT=3
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: LINT=true TEST=false
  exclude:
    - node_js: "6"
      env: ESLINT=6
